### ISSUE TITLE
Did theme variants change after 1.0?

### ISSUE THREAD

**Issue by elricsfate** [comfusion/after-dark#58]
After following the instructions for theme variants, I was unable to get them working. 

I performed the npm install in the theme folder, which seemed to install everything required. 

I then create `layouts/partials/head/critical-vendor.css`

After this I set `theme_variant = "hack solarized-dark"` in config.toml

At this point the colors simply turn white. It doesn't seem to matter what I set theme_variant to, it will only result in a white background.

Is there something I'm doing wrong?

**Comment by jhabdas** [comment]
@elricsfate thanks for calling this to my attention it was an error of omission while [updating the readme](https://github.com/comfusion/after-dark/commit/a5a33febab2bfd988bfc446d9c38c7c19650f73a#diff-04c6e90faac2675aa89e2176d2eec7d8R545) for 2.0. Please check out the linked diff linked and let me know if that doesn't provide enough clarification—I'd like to take some feedback in before I rev the docs again because I'm hoping to release a new minor soon. Thanks!

**Comment by elricsfate** [comment]
@jhabdas 

Thanks, I'll take a look at this tonight

**Comment by elricsfate** [comment]
@jhabdas 

So after looking at the line 547, I'm not following how that should be accomplished. global-styles.css is mentioned no hwere else in the file and a search for "global-styles.css hugo" doesn't display anything worthwhile.

Mind being a bit more verbose on that section? I understood the other parts.

**Comment by jhabdas** [comment]
@elricsfate updated the README. should be fairly clear now. thanks for your feedback.
