### ISSUE TITLE
suspicious-looking install script is suspicious

### ISSUE THREAD

**Issue by sudopluto** [comfusion/after-dark#75]
First of all, great job on this hack.css template for hugo. 

The install script could use some work however:
(note I am on Ubuntu 17.10)

- somehow bash wasnt used and thus the script failed (maybe try #!/bin/bash)?
- the flying toaster bit was very confusing
- submodule should be used to clone the theme
- default browser should be launched instead of elinks (xdg-open on linux and open on mac)

Once I finish up setting up my blog I will come back and make a pull request for what I think the script should look like. 

Thanks again for making this awesome theme for hugo!

**Comment by jhabdas** [comment]
Hi @sudopluto. Thank you, building After Dark has been fun. To date I've only tested it on macOS and Arch Linux. Sorry your installation experience wasn't as easy as intended.

I just tested on a 17.10 Ubuntu machine and it looks like you'll need to clone the source first then run the installation script locally after a `chmod +x ./after-dark/bin/install.sh`.

Regarding your suggestions, please note I've deliberately chosen not to rely on `git` when the finished product is installed which is why you do not see the theme installed using submodules. PRs which improve cross-platform compatibility, however, are gladly received against this issue.
