### ISSUE TITLE
exampleSite content

### ISSUE THREAD

**Issue by pbuzdin** [comfusion/after-dark#85]
Is it possible to provide exampleSite config with markdown pages and config showcasing all features?

This would be awesome!

**Comment by jhabdas** [comment]
You got it! 👍

**Comment by pbuzdin** [comment]
@jhabdas I would. I don't see any major differences or conflicts. 
I think all features and styles should be modularized to be turnable on or off in config (like https://github.com/comfusion/after-dark#bpg-image-support ).

**Comment by jhabdas** [comment]
I've marked this as help wanted. Going to close it for now as the Hack Cabin site linked from the readme should give users a good idea of what After Dark can do and because, frankly, I don't have time for this right now. I may decide to revisit this in the future.

On the plus side the documentation should help anyone looking to send in a pull request build out an example site using all of the documented features of the theme.
